### ISSUE TITLE
Tab test verbeterpunt

### ISSUE THREAD

**Issue by r20222** [r20222/lets-jam-webapplicatie#39]
Hover effecten van grafieken laten zien als je die tabt zodat data zichtbaar wordt (anders is de data niet zichtbaar voor mensen die niet kunnen hoveren)

**Comment by TessaViergever** [comment]
In de nieuwe grafiek is hoveren (nog niet mogelijk). Mocht het me lukken om dit nog toe te voegen in de CSS only grafiek za ik meenemen dat die data tabbaar is. Voor nu sluit ik de issue :)
