### ISSUE TITLE
Linkjes chartOceanRiver component

### ISSUE THREAD

**Issue by CathelijneVisser** [r20222/lets-jam-webapplicatie#51]
De flesjes zijn linkjes maar er staat geen aria label in dus nu hebben we linkjes zonder text ):

![Image](https://github.com/r20222/lets-jam-webapplicatie/assets/112855711/caf2834d-edc7-4a63-9ba3-0acf67e070f9)

**Comment by TessaViergever** [comment]
GEdaaaan. :)
